# Generated by Django 3.1.1 on 2020-09-05 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должно быть введено в формате: '+999999999'. Максимум 15 цифер.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
