# Generated by Django 3.1.1 on 2020-09-05 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200905_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+123456789'. Максимум 15 цифер.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
    ]
