# Generated by Django 3.1.1 on 2020-09-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200903_1003'),
        ('products', '0002_auto_20200901_1812'),
    ]

    operations = [
    ]
